version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: muzzlemed_mysql
    env_file: .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - muzzlemed_data_v2:/var/lib/mysql
  
  redis:
    image: redis:alpine
    container_name: muzzlemed_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  muzzlemed_data_v2: